-- Conocimiento (catálogo COMPLETO con handles reales) -> documentos.
-- Tras correr esto: node scripts/ingest-pendientes.js  (para vectorizar).
DELETE FROM public.documentos WHERE agente_id = '51d2d1fe-e8db-4388-9365-95cecb571517';
INSERT INTO public.documentos (client_id, agente_id, tipo, titulo, contenido, estado)
SELECT a.client_id, a.id, 'texto', v.titulo, v.contenido, 'pendiente'
FROM public.agentes a,
(VALUES
  ($s$Sobre DyeTales$s$, $s$Dye Tales es una marca chilena de lanas e hilados teñidos a mano (artesanales) para tejido. Lema: "Colores irrepetibles. Hechos una vez, para una sola persona: tú". Frase de marca: "La calidad no es un lujo, es nuestro punto de partida". Fundada por Sofi y Gus (tintoreros y tejedores) tras más de 20 años de experiencia en tejido; cada madeja se tiñe a mano en su taller en Chile. Misión: proveer lanas de alta calidad, únicas y teñidas con dedicación. Visión: crear una comunidad de tejedores y traer las mejores lanas del mundo a Chile. Valores: calidad y dedicación, sostenibilidad (fibras responsables) y comunidad. Marcas que representan: Dye Tales (propia, Chile), Ístex (Islandia) y Rosa Pomar / Retrosaria (Portugal).$s$),
  ($s$Contacto y puntos de venta$s$, $s$WhatsApp: +56973851002 | Email: dyetales@gmail.com | Instagram: @dyetales.cl. También en Pinterest, TikTok, X (Twitter) y YouTube. Podcast: Sofikints (Sofía Lindsay) sobre tejido, lanas, manualidades y vida rural. Puntos de venta físicos: Chile - Tienda Hilar, Paseo Los Dominicos, Las Condes, Santiago. Italia - Di lana e d'altre storie, Via Verrotti 130, Montesilvano, Pescara. Argentina - Crismar, Villegas 623, San Martín de Los Andes, Neuquén.$s$),
  ($s$Envíos y despacho$s$, $s$Hacen envíos a todo el mundo (internacional ~15 días hábiles). Envío GRATIS en compras sobre $100.000 en la Región Metropolitana y sobre $150.000 en otras regiones. Despachos los martes y jueves, tras confirmar pago y stock. Plazo en Chile: 1 a 3 días hábiles en ciudades; hasta 10 días hábiles en zonas rurales. Courier: Correos de Chile con seguimiento por email. Retiro en tienda: sin costo en Santiago, coordinando por WhatsApp +56973851002.$s$),
  ($s$Pagos y devoluciones$s$, $s$Medios de pago: Mercado Pago, con opción de 3 cuotas sin interés. Devoluciones: cambios/devoluciones dentro de 5 días hábiles por defectos del producto. Si la devolución es por preferencia del cliente, este asume los costos de envío.$s$),
  ($s$Guía de grosores de lana$s$, $s$Lace: chales etéreos y encajes. Fingering: calcetines, chales y proyectos con detalle. Sport: ropa de bebé, suéteres finos y accesorios. DK: prendas estructuradas (equilibrio entre ligereza y cuerpo). Worsted: suéteres, gorros y accesorios cálidos. Bulky: mantas, chaquetas y accesorios con textura marcada.$s$),
  ($s$Qué lana recomendar según el proyecto$s$, $s$Calcetines: Gretel (merino con nylon, más resistente) o Aurora (merino superwash). Bebé o prendas finas y suaves: La Pastora (baby alpaca + pima), Ella (merino sport) o Blancanieves (alpaca). Suéter islandés (lopapeysa): Léttlopi (DK), Plötulopi o Álafosslopi (más grueso). Opciones más económicas: Léttlopi y Fjallalopi ($9.900). Chales etéreos / encaje: Jazmine (kid mohair + seda) o Einband (lace). Para lavar tejidos terminados: Shampoo de bloqueo DyeTales o shampoo/acondicionador Istex.$s$),
  ($s$Lana Aurora (Fingering) — $19.900$s$, $s$Línea Aurora — Dye Tales (Chile). 100% Merino superwash 19 micras. Grosor Fingering. Madeja 100g / 400m. Precio $19.900. Ideal para chales, calcetines y prendas delgadas. Colores disponibles (enlace https://dyetales.cl/products/{handle}): Mar profundo (aurora-mar-profundo), Sueño sureño (aurora-sueno-sureno), Underground (aurora-underground), Verano naranja (aurora-verano-naranja), Mediterráneo (aurora-mediterraneo), Calipso (lana-aurora-calipso), Lavanda (lana-aurora-lavanda), Salvia (lana-aurora-salvia), Calameño (lana-aurora-calameno), Lilo y Stitch a $17.910 (lana-aurora-lilo-stich). Hay más colores que rotan según temporada; muchos pueden estar agotados.$s$),
  ($s$Lana Blancanieves (Fingering) — $23.700$s$, $s$Línea Blancanieves — Dye Tales (Chile). 100% Alpaca chilena. Grosor Fingering. Madeja 100g / 400m. Precio $23.700. Suave y abrigadora. Colores disponibles (https://dyetales.cl/products/{handle}): Clarito (lana-blancanieves-clarito), Barquillo (blancanieves-obispo-copia), Leelo Multipass (blancanieves-rosas-secas-copia), Rosas Secas (blancanieves-calipso-copia), Barbie Girl (lana-blancanieves-clarito-copia), Obispo (blancanieves-sandia-copia), Sandía (blancanieves-clarito-copia), Calipso (blancanieves-parmesano-copia).$s$),
  ($s$Lana Jazmine (Lace) — $20.900$s$, $s$Línea Jazmine — Dye Tales (Chile). 70% Kid Mohair + 30% Seda. Grosor Lace. Precio $20.900. Etérea y brillante, ideal para chales y para tejer en conjunto con otra lana. Colores disponibles (https://dyetales.cl/products/{handle}): Té con leche (lana-jazmine-te-con-leche), Ultra Violeta (lana-jazmine-ultra-violeta), Patito (lana-jazmine-patito), Flubber (lana-jazmine-flubber). Tiene muchos más tonos que suelen agotarse.$s$),
  ($s$Lana Ella (Sport) — $18.700$s$, $s$Línea Ella — Dye Tales (Chile). 100% Merino superwash. Grosor Sport. Madeja 100g / 300m. Precio $18.700. Ideal para suéteres finos y prendas de bebé. Color disponible (https://dyetales.cl/products/{handle}): Tomillo (lana-ella-tomillo).$s$),
  ($s$Lana Gretel (Fingering, ideal calcetines) — $18.700$s$, $s$Línea Gretel — Dye Tales (Chile). 90% Merino 19 micras + 10% Nylon. Grosor Fingering. Madeja 100g / 400m. Precio $18.700. El refuerzo de nylon la hace ideal para calcetines (más resistente al uso). Color disponible (https://dyetales.cl/products/{handle}): Cayena (lana-gretel-cayena).$s$),
  ($s$Lana La Pastora (Sport, baby alpaca) — $18.700$s$, $s$Línea La Pastora — Dye Tales (Chile). 70% Baby Alpaca + 30% Algodón Pima. Grosor Sport. Precio $18.700. Muy suave, ideal para bebé y prendas delicadas. Colores disponibles (https://dyetales.cl/products/{handle}): Beatriz (lana-la-pastora-beatriz), Elena (lana-la-pastora-elena), Catalina (lana-la-pastora-catalina), Inés (lana-la-pastora-ines).$s$),
  ($s$Lana Patagonia Sport (Corriedale) — $15.700$s$, $s$Línea Patagonia Sport — Dye Tales (Chile, Patagonia). 100% oveja Corriedale. Grosor Sport. Madeja 100g / 290m. Precio $15.700. Rústica y versátil. Colores disponibles (https://dyetales.cl/products/{handle}): Café con leche (lana-patagonia-sport-cafe-con-leche), Pampa (lana-patagonia-sport-pampa), Pampa 2 (lana-patagonia-sport-pampa-2), Puma (lana-patagonia-sport-puma), Té con Leche (lana-patagonia-sport-te-con-leche), Nácar (lana-patagonia-sport-nacar), Clarito (lana-patagonia-sport-clarito), Barquillo (lana-patagonia-sport-barquillo), Humita (lana-patagonia-sport-humita), Amarillo Fluor (lana-patagonia-sport-amarillo-fluor), Pistacho (lana-patagonia-sport-pistacho), Pistacho 2 (lana-patagonia-sport-pistacho-2), Leeloo Multipass (lana-patagonia-sport-leeloo-multipass), Lúcuma (lana-patagonia-sport-lucuma), Chirimoya alegre (lana-patagonia-sport-chirimoya-alegre), Cobre (lana-patagonia-sport-cobre), Barbie Girl (lana-patagonia-sport-barbie-girl), Rosa bebé (lana-patagonia-sport-rosa-bebe), Fresa (lana-patagonia-sport-fresa), Frambuesa (lana-patagonia-sport-frambuesa), Lilium (lana-patagonia-sport-lilium), Sandía (lana-patagonia-sport-sandia).$s$),
  ($s$Lana Patagonia Worsted (Corriedale) — $15.700$s$, $s$Línea Patagonia Worsted — Dye Tales (Chile, Patagonia). 100% oveja Corriedale. Grosor Worsted. Precio $15.700. Para suéteres, gorros y accesorios cálidos. Color disponible (https://dyetales.cl/products/{handle}): Blue (lana-patagonia-worsted-blue).$s$),
  ($s$Lana Léttlopi - Istex (DK) — $9.900$s$, $s$Línea Léttlopi — Istex (Islandia). 100% lana de oveja islandesa. Grosor DK. Madeja 50g / 100m. Precio $9.900 (de las más económicas). Clásica para suéteres islandeses (lopapeysa). Colores disponibles (https://dyetales.cl/products/{handle}): Humo 0054 (lana-lettlopi-humo-0054), Blanco 0051 (lana-lettlopi-blanco-0051), Amarillo 1703 (lana-lettlopi-amarillo-1703), Azul grisáceo 9418 (lana-lettlopi-azul-grisaceo-9418), Universo 1707 (lana-lettlopi-universo-1707), Mar 1700 (lana-lettlopi-mar-1700), Magenta 1705 (lana-lettlopi-magenta-1705), Lapislázuli 1403 (lana-lettlopi-lapislazuli-1403), Rojo granate 1409 (lana-lettlopi-rojo-granate-1409), Ocre oscuro 0867 (lana-lettlopi-ocre-oscuro-08672), Tostado 1419 (lana-lettlopi-tostado-1419), Negro 0059 (lettlopi-negro-0059), Púrpura 1414 (lana-lettlopi-purpura-1414).$s$),
  ($s$Lana Plötulopi - Istex (sin torcer) — $16.700$s$, $s$Línea Plötulopi — Istex (Islandia). 100% lana islandesa sin hilar (rústica y voluminosa). Madeja 100g / 300m. Precio $16.700. Para lopapeysa con técnica de lana sin torcer. Colores disponibles (https://dyetales.cl/products/{handle}): Ocre oscuro 1032 (lana-plotulopi-ocre-oscuro-1032), Café con leche 0009 (lana-plotulopi-cafe-con-leche-0009), Amarillo 1424 (lana-plotulopi-amarillo-1424), Chirimoya alegre 2028 (lana-plotulopi-chirimoya-alegre-2028), Rojo oxidado 1426 (lana-plotulopi-rojo-oxidado-1426), Naranja 1766 (lana-plotulopi-naranja-1766), Vino tinto 2027 (lana-plotulopi-vino-tinto-2027), Rojo oscuro 1427 (lana-plotulopi-rojo-oscuro-1427), Pelirrojo 1430 (lana-plotulopi-pelirrojo-1430), Rojo 0417 (lana-plotulopi-rojo-0417), Rosa 1425 (lana-plotulopi-rosa-1425), Bluegrass 2026 (lana-plotulopi-bluegrass-2026), Obispo 1428 (lana-plotulopi-obispo-1428), Azul oscuro 0118 (lana-plotulopi-azul-oscuro-0118), Azul eléctrico 1432 (lana-plotulopi-azul-electrico-1432), Océano 2022 (lana-plotulopi-oceano-2022), Azul 1431 (lana-plotulopi-azul-1431), Rey de reyes 9448 (lana-plotulopi-rey-de-reyes-9448), Turquesa 2025 (lana-plotulopi-turquesa-2025), Verde oscuro 0484 (lana-plotulopi-verde-oscuro-0484), Gris 9102 (lana-plotulopi-gris-9102), Oveja negra 1033 (lana-plotulopi-oveja-negra-1033), Negro azabache 0005 (lana-plotulopi-negro-azabache-0005), Negro 0059 (lana-plotulopi-negro-0059), Negro profundo 2024 (lana-plotulopi-negro-profundo-2024), Bosque oscuro 2020 (lana-plotulopi-bosque-oscuro-2020), Té con leche 0003 (lana-plotulopi-te-con-leche-0003), Blanco 0001 (lana-plotulopi-blanco-0001).$s$),
  ($s$Lana Fjallalopi - Istex (Sport) — $9.900$s$, $s$Línea Fjallalopi — Istex (Islandia). 100% oveja islandesa. Grosor Sport. Precio $9.900 (económica). Colores disponibles (https://dyetales.cl/products/{handle}): Verde glaciar 3024 (lana-fjallalopi-verde-glaciar-3024), Gris 3056 (lana-fjallalopi-gris-3056), Café profundo 3004 (lana-fjallalopi-cafe-profundo-3004), Verde esmeralda 3030 (lana-fjallalopi-verde-esmeralda-3030), Celeste 3022 (lana-fjallalopi-celeste-3022), Gris piedra 3058 (lana-fjallalopi-gris-piedra-3058), Rosa brumoso 3071 (lana-fjallalopi-rosa-brumoso-3071), Verde manzana 3032 (lana-fjallalopi-verde-manzana-3032), Azul cielo 3025 (lana-fjallalopi-azul-cielo-3025), Grosella roja 3061 (lana-fjallalopi-grosella-roja-3061), Blanco invierno 3054 (lana-fjallalopi-blanco-invierno-3054), Lila 3074 (lana-fjallalopi-lila-3074), Ladrillo 3042 (lana-fjallalopi-ladrillo-3042), Ruibarbo 3072 (lana-fjallalopi-ruibarbo-3072), Amarillo verano 3040 (lana-fjallalopi-amarillo-verano-3040), Café claro 3002 (fjallalopi-cafe-claro-3002), Cuervo negro 3059 (lana-fjallalopi-cuervo-negro-3059), Verde musgo 3031 (lana-fjallalopi-verde-musgo-3031), Blanco 3051 (lana-fjallalopi-blanco-3051), Azul eléctrico 3021 (lana-fjallalopi-azul-electrico-3021), Arena 3001 (lana-fjallalopi-arena-3001), Rojo oscuro 3060 (lana-fjallalopi-rojo-oscuro-3060), Morado 3073 (lana-fjallalopi-morado-3073), Café oscuro 3003 (lana-fjallalopi-cafe-oscuro-3003).$s$),
  ($s$Lana Álafosslopi - Istex (Bulky) — $15.900$s$, $s$Línea Álafosslopi — Istex (Islandia). 100% lana islandesa. Grosor Bulky. Precio $15.900. Gruesa, para proyectos rápidos y abrigados. Colores disponibles (https://dyetales.cl/products/{handle}): Tostado 1237 (lana-alafosslopi-tostado-1237), Bellota 0053 (lana-alafosslopi-bellota-0053), Jeans 0010 (lana-alafosslopi-jeans-0010), Verde azulado 9967 (lana-alafosslopi-verde-azulado-9967), Ámbar 9971 (lana-alafosslopi-ambar-9971), Beige Claro 0086 (lana-alafosslopi-beige-claro-0086), Blanco 0051 (lana-alafosslopi-blanco-0051), Montaña Verde 1230 (lana-alafosslopi-montana-verde-1230).$s$),
  ($s$Lana Einband - Istex (Lace) — $10.700$s$, $s$Línea Einband — Istex (Islandia). 100% lana islandesa. Grosor Lace. Precio $10.700. Fina, ideal para chales y para combinar. Colores disponibles (https://dyetales.cl/products/{handle}): Granada 9171 (lana-einband-granada-9171), Rojo 0047 (lana-einband-rojo-0047), Cherry 1769 (lana-einband-cherry-1769), Púrpura 9044 (lana-einband-purpura-9044), Cidra 9028 (lana-einband-cidra-9028), Jean Claro 0008 (lana-einband-jean-claro-0008), Ceniza 1026 (lana-einband-ceniza-1026), Beige 1038 (lana-einband-beige-1038), Avena 0885 (lana-einband-avena-0885), Azul Cielo 9281 (lana-einband-azul-cielo-9281), Turquesa 1762 (lana-einband-turquesa-1762), Azul Rey 9277 (lana-einband-azul-rey-9277), Chaqueta Jean 0010 (lana-einband-chaqueta-jean-0010), Gris Oscuro 9103 (lana-einband-gris-oscuro-9103), Azul Marino 0118 (lana-einband-azul-marino-0118).$s$),
  ($s$Lana Mondim - Rosa Pomar (Fingering, preventa) — $19.900$s$, $s$Línea Mondim — Rosa Pomar (Portugal). 100% lana fina portuguesa (oveja Campaniça), 3 cabos, NO superwash. Grosor Fingering. Madeja 100g / 385m. Precio $19.900. Producto en preventa. Colores disponibles (https://dyetales.cl/products/{handle}): B577 (lana-mondim-b577), M82 (lana-mondim-m82), 214 (lana-mondim-214), 212 (lana-mondim-212), B568 (lana-mondim-b568), C571 (lana-mondim-c571), C582 (lana-mondim-c582), B581 (lana-mondim-b581), A586 (lana-mondim-a586), 202 (lana-mondim-202), 204 (lana-mondim-204), 213 (lana-mondim-213), B580 (lana-mondim-b580), M97 (lana-mondim-m97), M96 (lana-mondim-m96), 500 (mondim-a572-copia-11), A567 (mondim-a572-copia-9), A576 (mondim-a572-copia-8), A578 (mondim-a572-copia-7), A582 (mondim-a572-copia-6), A587 (mondim-a572-copia-5), B579 (mondim-a572-copia-4), C580 (mondim-a572-copia-3), 119 negro (mondim-a572-copia-2), 302 (mondim-a572-copia-1).$s$),
  ($s$Lana Brusca - Rosa Pomar (DK) — $12.700$s$, $s$Línea Brusca — Rosa Pomar (Portugal). 50% lana Saloia + 50% Merino. Grosor DK. Precio $12.700. Colores disponibles (https://dyetales.cl/products/{handle}): a582 (lana-brusca-a582), c586 (lana-brusca-c586), a586 (lana-brusca-a586), a580 (lana-brusca-a580), b568 (lana-brusca-b568), 16b (lana-brusca-16b).$s$),
  ($s$Lana Vovó - Rosa Pomar (Sport) — $13.900$s$, $s$Línea Vovó — Rosa Pomar (Portugal). 100% lana fina portuguesa (oveja Campaniça). Grosor Sport. Precio $13.900. Colores disponibles (https://dyetales.cl/products/{handle}): 29 (lana-vovo-29), 20 (lana-vovo-20), 11 (lana-vovo-11), 6 (lana-vovo-6), 26 (lana-vovo-26), 80 (lana-vovo-80), 60 (lana-vovo-60).$s$),
  ($s$Accesorios, kits y suscripción$s$, $s$Caja Misteriosa Mensual de Dye Tales — $60.000 (caja-misteriosa-de-dye-tales): suscripción sorpresa mensual con lana seleccionada, patrón exclusivo y sorpresas; cupos limitados (variantes Blanco, Azul, Rosa, Dorado). Kit Whisper Sweater tallas 1-2 — $31.800 (suéter top-down sin costuras, incluye hilado Plötulopi; el patrón se vende aparte). Kit Whisper Sweater tallas 3-4 — $47.700. Bolso para proyectos de cuero — $37.000 (bolso-para-proyectos-de-cuero), hecho a mano en Futrono, 20x11x9 cm. Bolsa para proyectos Dye Tales — $5.700 (bolsas-para-proyectos-dye-tales). Enlace: https://dyetales.cl/products/{handle}$s$),
  ($s$Cuidado de tejidos (shampoo y acondicionador)$s$, $s$Shampoo de bloqueo Dye Tales Neutro 300 ml — $25.700 (handle: 1243), sin aroma, para fibras animales y vegetales. Shampoo de bloqueo Dye Tales Pink 300 ml — $25.700 (handle: 1244), aroma a rosas, para fibras animales (merino, alpaca, yak, cashmere) y vegetales. Shampoo de lana Istex 500 ml — $33.700 (handle: 1206), para lana islandesa, sin blanqueadores ni enzimas. Acondicionador de lana Istex 500 ml — $33.700 (handle: lana-1239), apto lavado a mano y máquina. Enlace: https://dyetales.cl/products/{handle}$s$),
  ($s$Talleres de tejido$s$, $s$Taller Brioche en Plötulopi — $37.000 (lana-taller-brioche-en-plotulopi): brioche en plano, 1 y 2 colores; incluye materiales (excepto palillos), desayuno y clase. Próximas fechas por confirmar. Taller Plötulopi Avanzado — $37.000 (lana-taller-plotulopi-avanzado): colorwork con lana sin torcer en circular; requisito saber tejer en redondo. Próximas fechas por confirmar. Consultar fechas por WhatsApp +56973851002.$s$),
  ($s$Preguntas frecuentes$s$, $s$¿Hacen envíos internacionales? Sí, a todo el mundo (~15 días hábiles). ¿Cuándo es gratis el envío en Chile? Sobre $100.000 en RM y sobre $150.000 en otras regiones. ¿Qué días despachan? Martes y jueves, tras confirmar pago y stock. ¿Puedo pagar en cuotas? Sí, 3 cuotas sin interés con Mercado Pago. ¿Puedo retirar en tienda? Sí, en Santiago sin costo, coordinando por WhatsApp +56973851002. ¿Las lanas son teñidas a mano? Sí, la mayoría: cada madeja es única ("colores irrepetibles") y puede haber leves variaciones de tono entre lotes.$s$)
) AS v(titulo, contenido)
WHERE a.id = '51d2d1fe-e8db-4388-9365-95cecb571517';
